### ISSUE TITLE
How does the size work?

### ISSUE THREAD

**Issue by mebibou** [CreativeBulma/bulma-tagsinput#23]
When using with an input like this:
```html
<input class="input is-small">
```

I was expecting the tags-input to keep the correct input size, but instead it became much bigger. Looking at the transformed html, I now have this:
```html
<div class="tags-input">
  <input class="input is-small">
</div>
```

But looking at the sass file, it seems the size will only work if `is-small` is applied on `.tags-input`, which is not the case here. Is it a bug? or an option to give when using `new BulmaTagsInput(selector, options);`

**Comment by mebibou** [comment]
Actually even when I add the `is-small` class on the `tags-input`, the input it still much bigger than it should

**Comment by greenhost87** [comment]
Same problem

**Comment by mebibou** [comment]
Temporary solution:
```scss
.tags-input {
  min-height: auto;

  .input {
    border: 0;
    height: initial;
    margin: initial;
  }
}
```
